FROM registry.access.redhat.com/ubi8/openjdk-17

VOLUME /orbit-api-volume

WORKDIR /home/jboss/

COPY . .

RUN chmod +x ./gradlew && \
    ./gradlew build && \
    mv ./app/build/libs/app-all.jar app.jar && \
    rm -rf build && \
    chmod +x ./app.jar


EXPOSE 8080

CMD ["java", "-jar", "app.jar"]

#CMD ["java", "-jar", "/home/jboss/app.jar"]