apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-api
spec:
  selector:
    matchLabels:
      app: orbit-api
  replicas: 1
  template:
    metadata:
      labels:
        app: orbit-api
    spec:
      containers:
        - name: orbit-api
          image: default-route-openshift-image-registry.apps-crc.testing/orbit-api/orbit-api:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: orbit-api
spec:
  selector:
    app: orbit-api
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: orbit-api
spec:
  to:
    kind: Service
    name: orbit-api
  port:
    targetPort: 8080